### PR TITLE
show hide password toggle for tabler theme auth ui updates

### PR DESCRIPTION
**Pull request by siberfx**
image

image

### CODE REVIEW

**Comment by jorgetwgroup** [comment]
Thanks for your support to the community i will ask @pxpm to check this PR.

Cheers.

**Comment by tabacitu** [comment]
Hi @siberfx ,

This is a cool feature, thanks! I'll categorize this as a COULD-DO for now, since it's the first time anybody asks for this. But since you provided a PR too, we're a lot closer to making it happen 😀 Thanks!

Everyone else - if you think this is a good idea please give a thumbs up to this. It will help us prioritize this.

@siberfx please do this in your own project for now. We'll test, review and possibly merge this later on. But right now we have a few MUSTs and SHOULDs that take up the whole team's time, so we've got to get back to those.

Thanks again, cheers!

**Comment by ziming** [comment]
From a product / onboarding perspective this is very useful

**Comment by promatik** [comment]
Hi @siberfx!
Thank you for your suggestion, I've reviewed and changed some things, the new PR is at #154, your commit history was preserved 👌

Let's move conversation about this feature there (#154).

**Pull request merged**
