### PR TITLE
Fix dark mode

### PR DESCRIPTION
**Pull request by jorgetwgroup**
This PR is to fix issues on this https://github.com/Laravel-Backpack/theme-tabler/issues/89 + other i find meanwhile working on fix.

Start with this. Image have not correctly borders:

Add-article-Backpack-Admin-Panel

Now it have:

Add-article-Backpack-Admin-Panel (1)

Cheers

### CODE REVIEW

**Comment by jorgetwgroup** [comment]
Fix alert.

From:
Dashboard-Backpack-Admin-Panel

To:
Dashboard-Backpack-Admin-Panel (1)

**Comment by jorgetwgroup** [comment]
Fix swal.

From:
Articles-Backpack-Admin-Panel

To:
Articles-Backpack-Admin-Panel (1)

**Comment by jorgetwgroup** [comment]
Fix CKEditor.

From:
Add-monster-Backpack-Admin-Panel

To:
Add-monster-Backpack-Admin-Panel (1)

**Comment by jorgetwgroup** [comment]
Fix EasyMDE.

From:
Add-monster-Backpack-Admin-Panel

To:
Add-monster-Backpack-Admin-Panel (1)

**Comment by jorgetwgroup** [comment]
Fix Select2 badge.

From:
Edit-pet-Backpack-Admin-Panel

To:
Edit-pet-Backpack-Admin-Panel (1)

**Comment by jorgetwgroup** [comment]
Fix Phone field.

From:
Screenshot 2023-07-07 at 08 47 35

To:
Screenshot 2023-07-07 at 08 48 04

**Comment by jorgetwgroup** [comment]
Fix Icon Picker.

From:
Screenshot 2023-07-07 at 08 49 55

To:
Screenshot 2023-07-07 at 08 50 40

**Comment by jorgetwgroup** [comment]
Fix border btn-file.

From:
Screenshot 2023-07-07 at 08 52 34

To:
Screenshot 2023-07-07 at 08 53 15

**Comment by jorgetwgroup** [comment]
Fix modal cancel color.

From:
Screenshot 2023-07-07 at 08 55 37

To:
Screenshot 2023-07-07 at 08 55 51

**Comment by jorgetwgroup** [comment]
Fix export.

From:
Screenshot 2023-07-07 at 08 57 31

To:
Screenshot 2023-07-07 at 08 57 45

**Comment by jorgetwgroup** [comment]
Fix visilibity.

From:
Screenshot 2023-07-07 at 09 00 02

To:
Screenshot 2023-07-07 at 09 00 14

**Comment by jorgetwgroup** [comment]
Fix floating header.

From:
Screenshot 2023-07-07 at 09 35 52

To:
Screenshot 2023-07-07 at 09 36 04

**Comment by jorgetwgroup** [comment]
Add this PR to fix charts: https://github.com/Laravel-Backpack/PRO/pull/180

**Comment by jorgetwgroup** [comment]
Still pending:

- [ ] On dashboard some text are too dark

Screenshot 2023-07-07 at 10 17 25

Screenshot 2023-07-07 at 10 17 33

- [ ] Make elfinder dark mode

Screenshot 2023-07-07 at 10 16 23

- [ ] Fix z-index icon picker

Screenshot 2023-07-07 at 10 17 01

- [ ] Make TinyMCE dark mode

Screenshot 2023-07-07 at 10 20 19

- [ ] Fix range color

Screenshot 2023-07-07 at 10 23 14

**Comment by jorgetwgroup** [comment]
Add this PR on this revision: https://github.com/Laravel-Backpack/CRUD/pull/5194

**Comment by tabacitu** [comment]
Excellent! I really like how you came through with this @jorgetwgroup . Not only fixed the ones I found, but found others too. Documented everything with screenshots. Created PR with what we can merge now. Excellent. Thank you 🙏

**Pull request merged**
