### PR TITLE
Fix dark mode overlay on elFinder iframe

### PR DESCRIPTION
**Pull request by jorgetwgroup**
This PR will fix dark mode on elFinder https://github.com/Laravel-Backpack/theme-tabler/issues/103

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @jorgetwgroup 

I've sent https://github.com/Laravel-Backpack/theme-tabler/pull/118 to address the colorMode issue. 

I've just asked for @promatik confirmation, I think there is no issue in making `colorMode` globally available.

After that PR gets merged you can access color mode with `window.parent.colorMode.result`, so something like:
`let theme = window.parent.colorMode?.result === 'dark' ? 'dark' : 'default';`

Cheers

**Comment by jorgetwgroup** [comment]
Hi @pxpm thank you very much about it, is almost work perfect, i update https://github.com/Laravel-Backpack/FileManager/pull/35 but im getting this error when i change color on menu:

Screenshot 2023-07-19 at 20 44 59

Look like for a while colorMode became null, but im using tabler, so can not be null.

Thanks again.

**Comment by jorgetwgroup** [comment]
> Hi @pxpm thank you very much about it, is almost work perfect, i update [Laravel-Backpack/FileManager#35](https://github.com/Laravel-Backpack/FileManager/pull/35) but im getting this error when i change color on menu:
> 
> Screenshot 2023-07-19 at 20 44 59
> Look like for a while colorMode became null, but im using tabler, so can not be null.
> 
> Thanks again.

this is fixed

**Comment by jorgetwgroup** [comment]
Fix the conflict

**Pull request merged**
